name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install broken-link-checker
      run: |
        sudo apt-get update
        sudo apt-get -y install npm
        sudo npm install broken-link-checker -g
    - name: Check broken links
      run: |
        blc -g -r https://docs.qovery.com
